/**
 * End-to-end lifecycle demo using the agent-sdk against the current adapter
 * (see contracts/DEPLOYMENTS.md for the live address — currently V3.2).
 *
 * - Lists open bounties
 * - Picks two open (non-agentOnly) ones
 * - Takes both as a human worker
 * - Pins a real result text to IPFS and submits work
 * - Approves both as the poster (same wallet — testnet demo only)
 *
 * Requires the same env as seed-bounties.ts plus one Pinata credential for
 * the SDK's pinText: PINATA_JWT (preferred) or PINATA_API_KEY + PINATA_SECRET.
 */

import { ArcBountyAgent, BOUNTY_ADAPTER_ABI, type BountyMeta } from "arcbounty-agent-sdk";
import { createPublicClient, createWalletClient, http, type Address, type Hash } from "viem";
import { privateKeyToAccount } from "viem/accounts";

const RPC     = process.env.ARC_TESTNET_RPC_URL!;
const PK      = process.env.PRIVATE_KEY as `0x${string}`;
const ADAPTER = process.env.BOUNTY_ADAPTER_ADDRESS as Address;

if (!RPC || !PK || !ADAPTER) {
  console.error("Missing env: ARC_TESTNET_RPC_URL / PRIVATE_KEY / BOUNTY_ADAPTER_ADDRESS");
  process.exit(1);
}

// The SDK's pinText prefers PINATA_JWT and falls back to the key/secret pair.
if (!process.env.PINATA_JWT && !(process.env.PINATA_API_KEY && process.env.PINATA_SECRET)) {
  console.error("Set PINATA_JWT (preferred) or PINATA_API_KEY + PINATA_SECRET for the SDK's pinText.");
  process.exit(1);
}

const RESULT_BODIES: Record<string, string> = {
  "Translate ArcBounty README to Spanish": `# README (traducción)

ArcBounty es un mercado de recompensas onchain construido sobre Arc Network,
donde tanto agentes autónomos como humanos pueden tomar tareas pagadas en
USDC. El escrow ocurre vía ERC-8183 AgenticCommerce, y la identidad de los
agentes se ancla a ERC-8004 IdentityRegistry.

## Empezar

1. Instala la dependencia: \`npm install arcbounty-agent-sdk\`.
2. Configura \`PRIVATE_KEY\`, \`PINATA_API_KEY\`, \`PINATA_SECRET\`.
3. Llama a \`agent.runOnce(filter, runTask)\` y deja que tu agente trabaje.

_(Demo translation — submitted automatically by the SDK lifecycle demo.)_
`,
  "Solidity gas-golf: optimize a simple voting contract": `# Voting contract — optimization notes

Without seeing the exact contract, the standard wins on \`vote()\` are:

1. **Pack \`Voter\` struct into a single 32-byte slot.** Combine \`bool voted\`
   (1 byte), \`uint8 votes\` (1 byte), and \`address delegate\` (20 bytes)
   into one slot — saves ~2,100 gas per SSTORE on first vote.
2. **Mark hot reads as \`immutable\` or \`constant\`** where possible — e.g.
   the candidate count if fixed at deploy time. Eliminates SLOAD on every
   vote.
3. **Use \`unchecked { ++count }\`** in 0.8.x to skip the overflow check on
   counters that cannot realistically overflow inside a single tx.
4. **Cache \`msg.sender\` into a local** if you reference it more than once;
   the compiler usually inlines it, but mixed paths sometimes miss.

Combined these typically land the ≥20% reduction. Submit the diff + the
Foundry gas report and we can verify exactness.

_(Demo submission — auto-generated by the SDK lifecycle demo.)_
`,
};

function pickResultBody(meta: BountyMeta, title: string): string {
  return RESULT_BODIES[title] ?? `Auto-generated demo submission for "${title}".\nJobId: ${meta.jobId}\n`;
}

async function fetchTitle(meta: BountyMeta): Promise<string> {
  // Description is markdown pinned at meta.ipfsDescHash. First line is "# <title>".
  try {
    const cid = meta.ipfsDescHash.replace(/^ipfs:\/\//, "");
    const res = await fetch(`https://gateway.pinata.cloud/ipfs/${cid}`);
    if (!res.ok) return `bounty-${meta.jobId}`;
    const text = await res.text();
    const firstLine = text.split("\n").find(l => l.startsWith("# "));
    return firstLine ? firstLine.replace(/^#\s+/, "").trim() : `bounty-${meta.jobId}`;
  } catch {
    return `bounty-${meta.jobId}`;
  }
}

async function main() {
  const agent = new ArcBountyAgent({
    privateKey: PK,
    rpcUrl: RPC,
    bountyAdapterAddress: ADAPTER,
  });
  console.log(`Worker address: ${agent.address}`);

  // 1. List open, human-eligible bounties (skip agentOnly since we're acting as a human)
  const open = await agent.listOpenBounties({ agentOnly: false, limit: 50 });
  console.log(`Open human-eligible bounties: ${open.length}`);

  if (open.length < 2) {
    console.error("Need at least 2 open human-eligible bounties.");
    process.exit(1);
  }

  // Pick the two cheapest fresh ones — minimizes risk if anything fails mid-flow.
  // Also include any bounty already taken by us but not yet submitted/approved, so
  // the script can be re-run after a mid-flow failure.
  const sorted = [...open].sort((a, b) => Number(a.reward - b.reward));
  const fresh = sorted.slice(0, 2);

  // Pull our own in-flight bounties (taken by us, not yet resolved) and prepend
  const mine = await agent.getMyBounties();
  const ours = mine.filter(m => !m.resolved && (
    !m.submittedResultHash || m.submittedResultHash.length === 0
  ));
  const seen = new Set<string>();
  const picks: BountyMeta[] = [];
  for (const m of [...ours, ...fresh]) {
    const k = m.jobId.toString();
    if (seen.has(k)) continue;
    seen.add(k);
    picks.push(m);
    if (picks.length >= 2) break;
  }

  // Annotate with title
  const annotated = await Promise.all(picks.map(async m => ({ meta: m, title: await fetchTitle(m) })));
  for (const { meta, title } of annotated) {
    console.log(`  → #${meta.jobId}  $${agent.formatUsdc(meta.reward)}  "${title}"`);
  }

  // 2. Take both as a human (agentId=0 by default since we never called register())
  for (const { meta, title } of annotated) {
    if (meta.isTaken && meta.assignedProvider.toLowerCase() === agent.address.toLowerCase()) {
      console.log(`\n[take] #${meta.jobId} "${title}" — already taken by us, skip`);
      continue;
    }
    console.log(`\n[take] #${meta.jobId} "${title}"`);
    const r = await agent.takeBounty(meta.jobId);
    console.log(`  tx: ${r.hash}`);
  }

  // 3. Pin + submit work for each (skip if already submitted)
  for (const { meta, title } of annotated) {
    const fresh = await agent.getBounty(meta.jobId);
    if (fresh.submittedResultHash && fresh.submittedResultHash.length > 0) {
      console.log(`\n[submit] #${meta.jobId} — already has submission, skip`);
      continue;
    }
    const body = pickResultBody(meta, title);
    console.log(`\n[submit] #${meta.jobId} pinning result (${body.length} bytes)…`);
    const r = await agent.submitWork(meta.jobId, { text: body });
    console.log(`  tx: ${r.hash}`);
  }

  // 4. Approve as poster (same wallet — fine for demo). approveBounty isn't on the
  //    agent-sdk surface since it's a poster-side action; call via raw writeContract.
  const account = privateKeyToAccount(PK);
  const wallet = createWalletClient({ account, transport: http(RPC), chain: undefined });
  const pub    = createPublicClient({ transport: http(RPC) });

  for (const { meta, title } of annotated) {
    const fresh = await agent.getBounty(meta.jobId);
    if (fresh.resolved) {
      console.log(`\n[approve] #${meta.jobId} "${title}" — already resolved, skip`);
      continue;
    }
    console.log(`\n[approve] #${meta.jobId} "${title}" → rep 90`);
    const hash: Hash = await wallet.writeContract({
      address: ADAPTER,
      abi: BOUNTY_ADAPTER_ABI,
      functionName: "approveBounty",
      args: [meta.jobId, 90],
      chain: null,
      account,
    });
    const rcpt = await pub.waitForTransactionReceipt({ hash });
    console.log(`  tx: ${hash}  status=${rcpt.status}`);
  }

  // 5. Final state
  console.log(`\nFinal state:`);
  for (const { meta: prev, title } of annotated) {
    const fresh = await agent.getBounty(prev.jobId);
    console.log(`  #${fresh.jobId} "${title}"  taken=${fresh.isTaken} resolved=${fresh.resolved}  result=${fresh.submittedResultHash || "(none)"}`);
  }

  console.log(`\nDone. USDC paid back to worker (= same wallet for this demo).`);
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
